### PR TITLE
added repeaterElement, refactored integration tests

### PR DESCRIPTION
**Pull request by sergueik**
Goal is to close the gap between [jProtractor locator snippets](https://github.com/sergueik/jProtractor/tree/master/src/main/resources) and [genuine protractor ones](https://github.com/angular/protractor/blob/master/lib/clientsidescripts.js)

Added delay and console feedback for PhantomJS tests.
Added method gBy.repeaterElement(repeater,row,binding)

### CODE REVIEW

**Comment by sergueik** [comment]
Why 'testFindSelectedtOption', 'testChangeSelectedtOption' fail in Travis, while passing locally plus adding some reader-friendly tests for the same - for next sprint

**Comment by caarlos0** [comment]
@sergueik please merge with master...

**Comment by caarlos0** [comment]
@sergueik about the tests, let me work a little on them first? I will see if can split them in more files, because it is getting too big already :package:

**Comment by sergueik** [comment]
Alexandro,

Please update the README.md 

the statement

``````
Can I use it yet?

Nope.
```  is alienating and hopefully no longer accurate!.
``````

**Comment by caarlos0** [comment]
@sergueik please open another issue to discuss that...

**Comment by sergueik** [comment]
The code have been merged, 
Feel free to modify the tests - currently its a mess. I plan to focus later on rca of tests failing  under travis/PhantomJS, lets leave these tests present but disabled.

**Comment by caarlos0** [comment]
Thanks

**Comment by sergueik** [comment]
i am doing basic test refactoring , so if you have not started yet maybe a good idea to hold to avoid effort duplication...

**Comment by caarlos0** [comment]
@sergueik OK, I didn't start yet, no, go ahead! :dancer:

**Pull request merged**
