### PR TITLE
pulling all recent code to next release

### PR DESCRIPTION
**Pull request by sergueik**
Added selectedRepeaterOption.js
cssContainingText.js

Provided the extra arguments for model.js to support testing pages with several Angular examples like ng-datepicker demo page.

Added various tests

### CODE REVIEW

**Comment by caarlos0** [comment]
let me know when it's ready to merge

**Comment by sergueik** [comment]
i forced failing tests to get skipped with `org.junit.Assume.*` while they do not behave the same on the desktop and under Travis.  I think the delta is worth merging.

**Comment by caarlos0** [comment]
Done

**Comment by caarlos0** [comment]
Hey @sergueik , I'll add you as contributor, so you have more freedom to improve the project.

Let me know if you disagree for any reason.

**Pull request merged**
