### PR TITLE
atempt  to merging jprotractor and Protractor-jvm

### PR DESCRIPTION
**Pull request by sergueik**
This is an attempt to collapse two projects that go largely in parallel

I sent the PR to Aaron "F1tZy" Van Prooyen  and have not heard back .

Also I am quite a bit ahead of his upstream project  F1tZ81/Protractor-jvm - 

developed and tested few more methods

Several updates to the core class. Methods implemented and tested:

binding.js
buttonText.js
evaluate.js
getLocationAbsUrl.js
model.js
options.js
partialButtonText.js
repeaterColumn.js
repeater.js
resumeAngularBootstrap.js
selectedOption.js
testForAngular.js
waitForAngular.js

Integration Tests implemented against http://way2automation.com/way2auto_jquery/index.php
and http://juliemr.github.io/protractor-demo

```
testCustomerLogin
testEvaluateTransactionDetails
testOpenAccount
testSortCustomerAccounts
testListTransactions
testAddCustomer
testAddition
```

No unit test in this revision...

### CODE REVIEW

**Comment by caarlos0** [comment]
@sergueik looks like there is a NPE somewhere...

**Comment by sergueik** [comment]
The errors are in integration tests communicating with PhantomJS driver. Not sure what can be done to make travis build green

**Comment by caarlos0** [comment]
@sergueik maybe this helps: https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by sergueik** [comment]
the errors are sporadic and not reproduced in local tests with phantomjs. I am about to comment the unstable tests that access the http://www.way2automation.com/angularjs-protractor/banking - added a handful of tests running local files.

**Comment by caarlos0** [comment]
@sergueik ok, thanks!

**Comment by sergueik** [comment]
Its time to update the README maybe

**Comment by caarlos0** [comment]
yeah,

I also thinking in add something like qulice to enforce code style/quality... what do you think?

**Comment by sergueik** [comment]
Alexandro,

I have not used it myself, will be happy to learn

**Comment by caarlos0** [comment]
@sergueik Ok, I'll implement that..

**Pull request merged**
